version: "3.8"

services:
  service-user:
    build: ./service-user
    ports:
      - 3001:3001
    depends_on:
      - db

  service-employee:
    build: ./service-employee
    ports:
      - 3002:3002
    depends_on:
      - db

  api-gateway:
    build: ./api-gateaway
    ports:
      - 3000:3000

  db:
    build: ./db
    environment:
      - POSTGRES_DB=apigateaway
      - POSTGRES_USER=postgresapi
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
